[package]
name = "hash-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
sha2 = "0.10.8"
sha3 = "0.10.8"
md5 = "0.7.0"
hex = "0.4.3"
dialoguer = "0.10.0"